dist: xenial
language: bash

branches:
  only:
    - master

notifications:
  email: false

addons:
  apt:
    packages:
      - build-essential
      - gcc
      - g++
      - make
      - automake
      - autoconf
      - libtool
      - curl
      - git

env:
  global:
    - TZ: "Asia/Shanghai"
    - VERSION: $(date +%Y%m%d)
    - TRAVIS_TAG: $VERSION

script:
  - bash build.sh x86_64
  - bash release.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: release/*
  file_glob: true
  overwrite: true
  skip_cleanup: true
  name: $VERSION
  #body: $TRAVIS_COMMIT_MESSAGE - automatically compile on $(date +'%F %T')
  on:
    branch: master
