dist: bionic
language: bash

branches:
  only:
    - master

notifications:
  email: false

addons:
  apt:
    packages:
      - build-essential
      - gcc
      - g++
      - make
      - automake
      - autoconf
      - libtool
      - curl
      - git

env:
  global:
    - TZ: "ROC"

script:
  - ./build.sh x86_64
  - ./deploy.sh
