version: 2
jobs:
  build:
    working_directory: ~/static-build-ci
    machine: true
    steps:
      - checkout
      - run:
          name: Prepare
          command: ./.circleci/prepare.sh
      - run:
          name: Run build
          command: ./build.sh x86_64
      - run:
          name: Deploy
          command: ./deploy.sh
      - store_artifacts:
          path: release
          destination: release
